name: Pancake
version: @version@
main: com.github.jenya705.pancake.Pancake
api-version: 1.16
depend: [ ProtocolLib, NBTAPI ]
authors: [ Jenya705 ]
description: Plugin OWA OWA OWA Pancake
commands:
  give:
    permission: pancake.command.give
    description: Give OWA OWA OWA Pancake
    usage: /give <selector> <item> [<count>=1]
  enchant:
    permission: pancake.command.enchant
    description: Enchant OWA OWA OWA Pancake
    usage: /enchant <selector> <enchant> [<level>=1]
permissions:
  pancake.*:
    default: op
    children:
      pancake.command.* : true
  pancake.command.*:
    default: op
    children:
      pancake.command.give: true
      pancake.command.enchant: true
  pancake.command.give:
    default: op
  pancake.command.enchant:
    default: op