package com.github.jenya705.pancake.enchantment;

import com.github.jenya705.pancake.enchantment.rarity.PancakeEnchantmentRarity;
import org.bukkit.enchantments.EnchantmentTarget;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Pancake enchantment annotation
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface PancakeEnchantment {

    /**
     *
     * Localized name of enchantment (e.g. Fire protection)
     *
     * @return Localized name of enchantment
     */
    String name();

    /**
     *
     * Id of enchantment (e.g. minecraft:fire_protection)
     *
     * @return Id of enchantment
     */
    String id();

    /**
     *
     * Enchantment target
     *
     * @return Enchantment target
     */
    EnchantmentTarget target();

    /**
     *
     * Enchantment rarity
     *
     * @return Enchantment rarity
     */
    float rarity() default PancakeEnchantmentRarity.COMMON_VALUE;

    /**
     *
     * Max level of enchantment can not be less than startLevel
     *
     * @return Max level of enchantment
     */
    int maxLevel() default 1;

    /**
     *
     * Start level of enchantment can not be more than maxLevel
     *
     * @return Start level of enchantment
     */
    int startLevel() default 1;

    /**
     *
     * IDs of enchantments which conflicts with this enchantment
     * If enchantment id is not in this array, it is not sign that they are not conflicts
     *
     * @return Enchantments conflicts
     */
    String[] conflicts() default {};

    /**
     *
     * Checks if this enchantment can be found in villager trades.
     *
     * @return true if the enchantment can be found in trades
     */
    boolean tradeable() default true;

    /**
     *
     * Checks if this enchantment can be found in an enchanting table or use to enchant items generated by loot tables.
     *
     * @return true if the enchantment can be found in a table or by loot tables
     */
    boolean discoverable() default true;

    /**
     * Checks if this enchantment is a treasure enchantment.
     * <br>
     * Treasure enchantments can only be received via looting, trading, or
     * fishing.
     *
     * @return true if the enchantment is a treasure enchantment
     */
    boolean treasure() default true;


}
